services:
  vue-app:
    build: .
    container_name: khmer_ttt_ui
    ports:
      - "80:80" # Expose App 1 on port 8081 for internal use
    environment:
      - PORT=80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
